apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "length-service.fullname" . }}-config
  labels:
    {{- include "length-service.labels" . | nindent 4 }}
data:
  OTEL_EXPORTER_OTLP_ENDPOINT: "{{ .Values.config.OTEL_EXPORTER_OTLP_ENDPOINT }}"
  OTEL_SERVICE_NAME: "{{ .Values.config.OTEL_SERVICE_NAME }}"
