apiVersion: v1
kind: Service
metadata:
  name: {{ include "length-service.fullname" . }}
  labels:
    {{- include "length-service.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort | default .Values.service.port }}
      protocol: TCP
      name: http
  selector:
    {{- include "length-service.selectorLabels" . | nindent 4 }}
